assignment1a first commit
feivornikolaou/Assignment-1 pull request #2
Opened 2023-02-13 16:23 UTC by feivornikolaou

Brief reason for profile solution

Mainlydigital admin- provides full control of salesforce, candidate onboarding Information and employer information. An admin will tackle problems with candidate data, onboarding application and other issue across the salesforce platform, hence why this profile is required. Cloned of System admin profile

Mainlydigital manager- Gives managers full access to candidate journeys, which includes the event where one manager isn't available and requires cover. Cloned of the solution manager profile

Mainlydigital candidate- Gives mainlydigital candidates the ability to track their journey. Cloned of the standard user profile and then restricted further.

2023-02-14 09:08 UTC, festusobadina requested changes
https://github.com/feivornikolaou/Assignment-1/blob/135cb5e6a05c631b241815ed37cf0eae747e8469/force-app/main/default/layouts/Template__c-Template%20Layout.layout-meta.xml#L72

I was not able to deploy the code properly because after you changed the variable name on `Template Task` from `Task` to `Requirements`, the `Template Task Layout` is still referencing the old field name.

Pull the latest version of the this file from your org and push that to Git and I will be able to deploy it properly.

2023-02-14 09:14 UTC, festusobadina commented
https://github.com/feivornikolaou/Assignment-1/blob/135cb5e6a05c631b241815ed37cf0eae747e8469/force-app/main/default/customindex/Journey__c.Candidate_Email_Address__c.indx-meta.xml#L1

The `customindex` folder is still present in your Git repo main branch. Double check its not in your local directory, then you need delete it from your Git one. You can do this from the website by navigating to the `Code` section, finding the folder and deleting it.

![image](https://user-images.githubusercontent.com/82383713/218690842-39fd9429-fb3b-4621-800b-ef564520ed99.png)

2023-02-14 16:08 UTC, festusobadina commented
https://github.com/feivornikolaou/Assignment-1/blob/a89b21dd577ecd1f355748c989ba0ac17e639acb/force-app/main/default/objects/Journey__c/Journey__c.object-meta.xml#L145

Your `Journey`, `Journey Task` and `Template Task` objects are still marked as `In Development`, so when I tried testing the app from the `Manager` and `Candidate` perspectives they would not show up. 

I can schedule a call with you to show you how you can test these changes and notice this error yourself.

2023-02-14 16:10 UTC, festusobadina requested changes
> Brief reason for profile solution

> Mainlydigital admin- provides full control of salesforce, candidate onboarding Information and employer information. An admin will tackle problems with candidate data, onboarding application and other issue across the salesforce platform, hence why this profile is required. Cloned of System admin profile

> Mainlydigital manager- Gives managers full access to candidate journeys, which includes the event where one manager isn't available and requires cover. Cloned of the solution manager profile

> Mainlydigital candidate- Gives mainlydigital candidates the ability to track their journey. Cloned of the standard user profile and then restricted further.

This is a description of each profile, not _why_ you chose to use profiles.

2023-02-14 16:10 UTC, festusobadina commented on force-app/main/default/profiles/Mainlydigital admin.profile-meta.xml
> +    <description>Provides full control of salesforce, candidate onboarding Information and employer information.An admin will tackle problems with candidate data, onboarding application and other iss
The first sentence was enough for the description. Remember to keep them as short as possible, the job of an admin is already quite apparent.

2023-02-14 16:10 UTC, festusobadina commented on force-app/main/default/profiles/Mainlydigital manager.profile-meta.xml
> +    <description>Gives managers full access to candidate journeys, which includes the event where one manager isn&apos;t available and requires cover.</description>
> Gives managers full access to _all_ candidate journeys

This would be a more succinct version.

2023-02-14 16:10 UTC, festusobadina commented on force-app/main/default/profiles/Mainlydigital candidate.profile-meta.xml
> +    <description>Gives mainlydigital candidates the ability to track their journey.</description>
Good description, useful while still being brief.

2023-02-14 16:10 UTC, festusobadina commented on force-app/main/default/profileSessionSettings/Mainlydigital_admin_profileSessionSetting1676250185493.profileSessionSetting-meta.xml
> +    <profile>Mainlydigital admin</profile>
Admin, Manager and Candidates are titles in this scenario, so they deserve capital letters. Especially in the label of a profile.

2023-02-14 16:10 UTC, festusobadina commented on force-app/main/default/profiles/Mainlydigital candidate.profile-meta.xml
> +        <visibility>Hidden</visibility>
The `Journey` and `Journey Task` objects are set to `Tab Hidden`. This means that a candidate cannot access their journey.

2023-02-14 16:10 UTC, festusobadina commented on force-app/main/default/profiles/Mainlydigital manager.profile-meta.xml
> +        <visibility>Hidden</visibility>
All of the tabs for the manager are set to `Tab Hidden`. This means that none of the objects are available for use via the UI.

2023-02-14 16:10 UTC, festusobadina commented on force-app/main/default/profiles/Mainlydigital candidate.profile-meta.xml
> +<?xml version="1.0" encoding="UTF-8"?>
> Their sole reason for accessing the Salesforce instance is to follow an onboarding journey.

Should a candidate have access to a majority of standard tabs if their sole purpose is to follow an onboarding journey?

2023-02-27 15:20 UTC, festusobadina approved these changes
> > Brief reason for profile solution
> 
> > Mainlydigital admin- provides full control of salesforce, candidate onboarding Information and employer information. An admin will tackle problems with candidate data, onboarding application and other issue across the salesforce platform, hence why this profile is required. Cloned of System admin profile
> 
> > Mainlydigital manager- Gives managers full access to candidate journeys, which includes the event where one manager isn't available and requires cover. Cloned of the solution manager profile
> 
> > Mainlydigital candidate- Gives mainlydigital candidates the ability to track their journey. Cloned of the standard user profile and then restricted further.
> 
> This is a description of each profile, not _why_ you chose to use profiles.

Please include your justification for your approach.

2023-02-27 16:09 UTC, feivornikolaou commented
Reason- I cloned profiles (minimum user for candidate, solution manager for manager and system admin for admin) to implement the permissions for listed on the assignment brief for each user, and in the future, permission sets can be used for addition privileges.

2023-02-27 16:10 UTC, merged